apiVersion: batch/v1
kind: CronJob
metadata: 
  name: data-migration-syncup
  namespace: dev
spec:
  schedule: "0 5 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: data-migration-syncup
            image: data-migration:1.5